#!/usr/bin/env bash
# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Per-test Xcelium runner for the RISC-V compliance suite.
# Two calling interfaces are supported:
#
#   Direct ELF (for ad-hoc use):
#     ./run_xlm.sh <test.elf>
#
#   Compliance Makefile (RUN_TARGET interface):
#     ./run_xlm.sh --raminit=<vmem_file> [--term-after-cycles=<n>]
#     (--term-after-cycles is silently ignored; xrun uses the 10M-cycle watchdog in the TB)
#
# SIGNATURE lines emitted by riscv_testutil ($display) appear on stdout so
# the compliance Makefile can grep and compare them.
#
# VMem format note:
#   objcopy -O verilog --verilog-data-width=4 emits:
#     - @addresses in BYTE units    (but $readmemh treats them as WORD/array indices)
#     - data words with bytes in memory order (LSB first in hex, i.e. byte-swapped vs what
#       $readmemh expects for a 32-bit big-endian hex interpretation)
#   This script fixes both issues with an awk pass before calling xrun.
#
# Optional env vars:
#   RISCV_PREFIX      - toolchain prefix (default: riscv32-unknown-elf-)
#   COVERAGE_ARGS     - base coverage args WITHOUT -covtest (set by run_all_xlm.sh -c)
#                       e.g. "-covmodeldir /path -covworkdir /path -covscope compliance"
#   XLM_DIR           - path to the elaborated xcelium.d library

set -e

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
XLM_DIR="${XLM_DIR:-${SCRIPT_DIR}/xlm_compliance_out}"
RISCV_PREFIX="${RISCV_PREFIX:-riscv32-unknown-elf-}"

VMEM=""
ELF=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --raminit=*) VMEM="${1#--raminit=}" ;;
    --term-after-cycles=*) ;;  # ignored; TB watchdog handles timeout
    *) ELF="$1" ;;
  esac
  shift
done

# Temporary files (cleaned up on exit).
TMP_RAW=$(mktemp /tmp/ibex_raw_XXXXXX.vmem)
TMP_FIXED=$(mktemp /tmp/ibex_fixed_XXXXXX.vmem)
TMP_LOG=$(mktemp /tmp/ibex_xrun_XXXXXX.log)
trap 'rm -f "$TMP_RAW" "$TMP_FIXED" "$TMP_LOG"' EXIT

if [[ -n "$ELF" && -z "$VMEM" ]]; then
  # Direct ELF interface: generate raw vmem from the ELF.
  if [[ ! -f "$ELF" ]]; then
    echo "Error: ELF file not found: $ELF" >&2; exit 1
  fi
  "${RISCV_PREFIX}objcopy" -O verilog --verilog-data-width=4 "$ELF" "$TMP_RAW"
elif [[ -n "$VMEM" ]]; then
  # Compliance Makefile interface: vmem already generated by COMPILE_TARGET.
  if [[ ! -f "$VMEM" ]]; then
    echo "Error: vmem file not found: $VMEM" >&2; exit 1
  fi
  cp "$VMEM" "$TMP_RAW"
else
  echo "Usage: $0 <test.elf>  OR  $0 --raminit=<vmem> [--term-after-cycles=<n>]" >&2
  exit 1
fi

# VMem format depends on which path generated the file:
#
#   ELF/objcopy path (direct ELF interface):
#     objcopy -O verilog --verilog-data-width=4 emits BYTE addresses and writes bytes
#     in memory order (LSB first in the 8-hex-digit word).  Two fixups needed before
#     $readmemh: divide @addresses by 4 (byte → word index) and byte-swap each word.
#
#   Compliance Makefile path (--raminit interface):
#     srec_cat -byte-swap 4 already emits WORD addresses and big-endian word data that
#     $readmemh can load directly into a 32-bit wide memory.  No transformation needed.
if [[ -n "$ELF" ]]; then
  awk '
  /^@/ {
    addr = strtonum("0x" substr($0, 2))
    printf "@%08x\n", addr / 4
    next
  }
  {
    for (i = 1; i <= NF; i++) {
      w = $i
      printf "%s%s%s%s%s", substr(w,7,2), substr(w,5,2), substr(w,3,2), substr(w,1,2), \
             (i < NF ? " " : "\n")
    }
  }' "$TMP_RAW" > "$TMP_FIXED"
else
  # srec_cat vmem: word-addressed and correct byte order, but may have multiple
  # data words per @addr line.  Normalise to one word per line so the testbench's
  # inline vmem parser (which reads one token per $fgets/$sscanf pass) works correctly.
  awk '
  /^\// { next }
  NF == 0 { next }
  /^@/ {
    printf "@%s\n", substr($1, 2)
    for (i = 2; i <= NF; i++) printf "%s\n", $i
    next
  }
  { print }' "$TMP_RAW" > "$TMP_FIXED"
fi

# Derive a per-test unique name from the source vmem/elf filename.
# Used as the -covtest name so sequential test runs don't collide in the coverage DB.
src_file="${VMEM:-$ELF}"
test_name=$(basename "${src_file}" .vmem)
test_name="${test_name%.elf}"

if [[ -n "${COVERAGE_ARGS:-}" ]]; then
  # run_all_xlm.sh sets COVERAGE_ARGS without -covtest; append the per-test name here.
  cov_args="${COVERAGE_ARGS} -covtest ${test_name}"
else
  # Build was done with -coverage all but we're not collecting; route coverage output
  # to a per-test temp dir so consecutive tests don't collide on ./cov_work/scope/test.
  tmp_covdir=$(mktemp -d /tmp/xlm_cov_XXXXXX)
  trap 'rm -rf "$tmp_covdir"' EXIT
  cov_args="-covworkdir ${tmp_covdir} -covtest t"
fi

# Use -l to route ALL xrun/xmsim output (including RTL $display/SIGNATURE lines) to
# a temp log file.  With coverage args, xcelium stops flushing $display to stdout, so
# -l is required.  Redirect xrun's own stdout to /dev/null to avoid duplication: with
# -l, xcelium echoes $display to BOTH the logfile and its own stdout.  Without the
# redirect, run_xlm.sh's stdout would carry both the echo (36 lines) and the grep
# output below (36 lines) = 72 lines total in the compliance signature file.
set +e
xrun \
  -64bit \
  -R \
  -l "${TMP_LOG}" \
  -xmlibdirname "${XLM_DIR}/xcelium.d" \
  -licqueue \
  +MEMFILE="${TMP_FIXED}" \
  ${cov_args} \
  > /dev/null
_xrun_status=$?
set -e

# Report failures.  Everything xrun prints goes to TMP_LOG, xrun's own stdout goes
# to /dev/null, and the EXIT trap deletes TMP_LOG -- so without this block a failed
# run leaves a 0-byte .stdout, a 0-byte .log and no indication of the cause at all.
# The compliance Makefile does not check exit status either, so ~50 tests x 5 ISA
# variants would each fail silently while still paying full simulator startup.
# That cost real debugging time on 2026-09-18; keep the diagnostics.
if [ "${_xrun_status}" -ne 0 ]; then
  {
    echo "run_xlm.sh: xrun exited ${_xrun_status}"
    echo "run_xlm.sh:   lib   = ${XLM_DIR}/xcelium.d"
    echo "run_xlm.sh:   memfile = ${TMP_FIXED}"
    echo "run_xlm.sh: --- last 40 lines of the xrun log ---"
    tail -40 "${TMP_LOG}" 2>/dev/null
  } >&2
  exit "${_xrun_status}"
fi

# Forward SIGNATURE lines to stdout so the compliance Makefile can grep them.
# A run that completes but emits no signature is also a failure worth naming:
# bare `grep` would exit 1 under `set -e` and abort just as silently.
if ! grep "^SIGNATURE:" "${TMP_LOG}"; then
  {
    echo "run_xlm.sh: xrun completed but produced no SIGNATURE lines."
    echo "run_xlm.sh: --- last 40 lines of the xrun log ---"
    tail -40 "${TMP_LOG}" 2>/dev/null
  } >&2
  exit 1
fi
