#!/usr/bin/env bash
# Regenerate cms_xlm.f, the explicit file list Xcelium builds the bench from, out of cms_dv.f (the
# Verilator list, which finds library modules with -y). Run from anywhere, inside
# `nix develop .#vlt_shell` (needs verilator and python3): make filelist. An argument writes the
# list elsewhere (make lint uses that to check the committed list is current).
#
# Verilator elaborates cms_tb and records every file it read; the list keeps the explicit files of
# opentitan-cheriot/cheriot_rtl.f first, in their order (the packages), then every other library
# file that declares a module, interface or package, then the testbench files of cms_dv.f. Include
# files (prim_assert.sv and the like) are left to +incdir.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SUPER_DIR="$(realpath "${SCRIPT_DIR}/../../..")"
cd "${SUPER_DIR}"
tmp=$(mktemp -d /tmp/cms_filelist_XXXXXX)
trap 'rm -rf "${tmp}"' EXIT
verilator --json-only --timing -Wno-fatal -Wno-lint -Wno-style -Wno-COVERIGN -Wno-UNOPTFLAT \
  --Mdir "${tmp}" --top-module cms_tb -f ibex/dv/cheriot-mem-subsys/cms_dv.f >/dev/null
OUT="${1:-ibex/dv/cheriot-mem-subsys/cms_xlm.f}"
python3 - "${tmp}/Vcms_tb.tree.meta.json" > "${OUT}" <<'PY'
import json, re, sys
def plain(f):
    out = []
    for line in open(f):
        line = line.split("//")[0].strip()
        if line and not line.startswith(("-", "+")):
            out.append(line)
    return out
def incdirs(f):
    return [l.strip() for l in open(f) if l.strip().startswith("+incdir+")]
rtl_f, tb_f = "opentitan-cheriot/cheriot_rtl.f", "ibex/dv/cheriot-mem-subsys/cms_dv.f"
ordered, tb = plain(rtl_f), plain(tb_f)
read = {v["filename"] for v in json.load(open(sys.argv[1]))["files"].values()}
decl = re.compile(r"^\s*(module|interface|package|program)\b", re.M)
lib = sorted(f for f in read
             if f.endswith((".sv", ".v")) and f not in ordered and f not in tb
             and decl.search(open(f).read()))
print("// GENERATED by gen_xlm_filelist.sh from cms_dv.f -- do not edit; run 'make filelist'.")
print("// Paths relative to the ibex_cheriot_verification root (cms_xlm_build.sh runs xrun there).")
for d in incdirs(rtl_f) + incdirs(tb_f):
    print(d)
print("// opentitan-cheriot/cheriot_rtl.f, in order")
print("\n".join(ordered))
print("// library modules (found with -y by Verilator)")
print("\n".join(lib))
print("// testbench")
print("\n".join(tb))
PY
echo "wrote ${OUT} ($(grep -vc '^//' "${OUT}") lines)"
